# Generated by Django 5.0.14 on 2026-07-26 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(default='Senior Software Engineer', max_length=150)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=75.0, max_digits=8)),
                ('max_weekly_hours', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=150)),
                ('priority', models.IntegerField(default=3, help_text='Priority scale from 1 (Low) to 5 (Critical)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('budget', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database & Cloud'), ('ai_ml', 'AI / ML & Data'), ('devops', 'DevOps & Security'), ('mobile', 'Mobile Development')], default='backend', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SolverRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('objective_used', models.CharField(choices=[('balanced', 'Balanced (Skill + Priority + Bench)'), ('maximize_fit', 'Maximize Skill Fit Quality'), ('maximize_priority', 'Prioritize High-Priority Projects'), ('minimize_bench', 'Minimize Bench Time'), ('minimize_cost', 'Minimize Hourly Cost')], default='balanced', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_score', models.FloatField(default=0.0)),
                ('runtime_seconds', models.FloatField(default=0.0)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary_metrics', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headcount_needed', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('weekly_hours_required', models.IntegerField(default=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='staffing.project')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocated_hours', models.IntegerField(default=40)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='staffing.developer')),
                ('project_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='staffing.projectslot')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(default=3, help_text='Proficiency scale from 1 (Novice) to 5 (Expert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='staffing.developer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='staffing.skill')),
            ],
            options={
                'unique_together': {('developer', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(related_name='developers', through='staffing.DeveloperSkill', to='staffing.skill'),
        ),
        migrations.CreateModel(
            name='SlotSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_proficiency', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_mandatory', models.BooleanField(default=True)),
                ('project_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='staffing.projectslot')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_requirements', to='staffing.skill')),
            ],
            options={
                'unique_together': {('project_slot', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='projectslot',
            name='required_skills',
            field=models.ManyToManyField(related_name='slots', through='staffing.SlotSkillRequirement', to='staffing.skill'),
        ),
        migrations.CreateModel(
            name='AllocationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.FloatField(default=0.0)),
                ('solver_algorithm', models.CharField(choices=[('cpsat', 'Google OR-Tools CP-SAT Solver'), ('greedy', 'Naive Greedy Matcher'), ('scipy', 'SciPy Bipartite Matcher')], default='cpsat', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='staffing.developer')),
                ('project_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='staffing.projectslot')),
                ('solver_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='staffing.solverrun')),
            ],
        ),
    ]
