# Generated by Django 5.0.14 on 2026-08-05 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_leave_approval_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='staffing.developer'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='project_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='staffing.projectslot'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['developer', 'status', 'start_date', 'end_date'], name='alloc_dev_stat_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='alloc_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='developerleave',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='projectslot',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='slot_end_after_start'),
        ),
    ]
